export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGOUT_USER = 'LOGOUT_USER';
export const ISLOGGED_IN = 'ISLOGGED_IN';
export const FILTER_PAIRS = 'FILTER_PAIRS';
export const FETCH_PAIRS = 'FETCH_PAIRS';
export const ORDERBOOK_TYPE = 'ORDERBOOK_TYPE';
export const CHANGE_PAIR = 'CHANGE_PAIR';
export const CHANGE_PAIR_FUTURE = 'CHANGE_PAIR_FUTURE';
export const CHANGE_PAIR_MARGIN = 'CHANGE_PAIR_MARGIN';
export const PICK_RATE_MARGIN = 'PICK_RATE_MARGIN';
export const DEPOSITALERT = 'DEPOSIT_ALERT';
export const ISDEPOSITACTIVE = 'DEPOSIT_ACTIVE';
export const DERQUIZALERT = 'DERIVATIVE_QUIZ_ALERT';
export const CHART_HEIGHT = 'CHART_HEIGHT';


export const SET_PAIRMENU_MODAL = 'SET_PAIRMENU_MODAL';
export const SET_DERIVATIVEPAIR_MODAL = 'SET_DERIVATIVEPAIR_MODAL';
export const FILTER_WALLET = 'FILTER_WALLET';
export const FETCH_WALLET = 'FETCH_WALLET';
export const LOGOUT_ACTION = 'LOGOUT_ACTION';

export const FILTER_TRADERS = 'FILTER_TRADERS';
export const FETCH_TRADERS = 'FETCH_TRADERS';
export const FETCH_FAVORITES = 'FETCH_FAVORITES';
export const TRADE_HISTORY = 'TRADE_HISTORY';
export const PICK_RATE = 'PICK RATE';
export const ORDER_SIDE = 'ORDER SIDE';
export const MARGIN_ORDER_SIDE = 'MARGIN_ORDER_SIDE';



export const PAIRS = {
    SET: "PAIRS_SET",
    SET_ALL: "PAIRS_SET_ALL",
    SET_ALL_STATIC: "SET_ALL_STATIC",
    SET_USER_LEVEAGE_SETTINGS: "SET_USER_LEVEAGE_SETTINGS",
    DEPTH_CHART: 'DEPTH_CHART'

}

export const USER_DATA = {
    SET_WALLETS: "SET_WALLETS", // Spot
    SET_WALLETS_FUTURE: "SET_WALLETS_FUTURE", // Future
    SET_WALLETS_MARGIN: "SET_WALLETS_MARGIN", // Margin
    SET_ORDERS: "SET_ORDERS",
    SET_USER_POSITIOn: "SET_USER_POSITIOn",
    SET_USER_Margin_POSITION: "SET_USER_Margin_POSITION",
    SET_ORDERS_FUTURE: "SET_ORDERS_FUTURE",
    SET_FUTURE_LEVERAGE: "SET_FUTURE_LEVERAGE",
    SET_USER_SETTINGS: "SET_USER_SETTINGS",
    SET_ACTIVE_TAB: "SET_ACTIVE_TAB",
    SET_ACCOUNT_INFO: "SET_ACCOUNT_INFO",

    SET_USER_IMAGE:"SET_USER_IMAGE",


}


export const FAV_PAIRS = {
    SET: 'SET_FAV_PAIR'
}

export const CURRENT_LANGUAGE = {
    SET: 'SET_CURRENT_LANGUAGE'
}

export const CURRENCIES = {
    SET: 'SET_CURRENCIES',
    OVERVIEW_CURRENCY_ID: 'OVERVIEW_CURRENCY_ID'
}

export const FIATCURRENCIES = {
    SET: 'SET_FIATCURRENCIES'
}