declare module 'react-native-common-date-picker';
declare module 'react-native-snap-carousel';
declare module 'expo-chart-kit';
declare module 'react-native-echarts-wrapper'
declare module 'react-native-form-validator'
declare module 'crypto-js/sha256'
declare module 'crypto-js/hmac-sha512'
declare module 'crypto-js/enc-base64'
declare module 'crypto-js/hmac-sha256'
declare module 'react-native-google-recaptcha-v2';
declare module 'react-native-calendar-picker';
declare module 'firebase';
declare module 'react-native-uuid';
declare module '@gorhom/portal';